name: Proto2Prod CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Bootstrap platform
        run: make bootstrap
      - name: Run platform checks
        run: make proto2prod-check
      - name: Package release
        run: make package
